version: '3'
services:
  flyway:
    image: info7205group4/db:flyway
    environment:
    - FLYWAY_URL=jdbc:postgresql://${Hostname}:${Port}/${DBName}
    - FLYWAY_USER=${Username}
    - FLYWAY_PASSWORD=${Password}
    - FLYWAY_SCHEMAS=${Schema}
    depends_on:
      - postgres
  postgres:
    image: info7205group4/db:postgres_database
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=${Username}
    - POSTGRES_PASSWORD=${Password}
    - POSTGRES_DB=${DBName}
