CREATE TABLE List(
   List_Id SERIAL PRIMARY KEY,
   Name           TEXT    NOT NULL,
   Created_AtTime  TIMESTAMP WITH TIME ZONE    DEFAULT CURRENT_TIMESTAMP NOT NULL,
   Updated_AtTime   TIMESTAMP WITH TIME ZONE   DEFAULT CURRENT_TIMESTAMP NOT NULL,
   UserId INT,
   CONSTRAINT fk_customer
      FOREIGN KEY(userid) 
	  REFERENCES users(userid)
);